react-images => react-bnb-gallery
Scrivito/scrivito_example_app_js pull request #334
Opened 2020-09-15 13:21 UTC by apepper

`ThumbnailGallery` previously used [`react-images`](https://www.npmjs.com/package/react-images). Now it uses [`react-bnb-gallery`](https://www.npmjs.com/package/react-bnb-gallery).

According to [`react-images`](https://www.npmjs.com/package/react-images)'s own readme:

> ⚠️  Warning!
>
> Don't use this in a new project. This package hasn't been properly maintained in a long time and there are much better options available.

So we needed a replacement.

Thankfully @pietruszka found a good library, that is quite an easy replacement: [`react-bnb-gallery`](https://www.npmjs.com/package/react-bnb-gallery). It works very similar to `react-images` and with a few tweaks looks at least similar.

### Screenshots

*Previously*
<img width="1552" alt="react-images" src="https://user-images.githubusercontent.com/86275/93215496-c9a54d80-f766-11ea-9f52-84f2fd52f64e.png">

*Now*
<img width="1552" alt="react-bnb-gallery" src="https://user-images.githubusercontent.com/86275/93215512-ce6a0180-f766-11ea-99cb-3fcbeb5ca57e.png">

### Open Todos
* [x] Check if it works fine with latest react version (without warnings)
* [ ] Check if it works fine with IE11.
* [ ] Check bundle size.

2020-09-16 13:44 UTC, agessler commented
@apepper From my site ok. I changed by CSS the font-family and the background color of the overlay. I don't like to use `!important` that much. I would like to prefer changing more tags or reduce inline CSS styles.
The Font issue results of an `<h3>` use in the template I could not access. Overlay has inline CSS color hard coded.

2020-09-17 06:48 UTC, apepper commented
@agessler Thanks for your design improvements.

> I changed by CSS [...] the background color of the overlay. I don't like to use !important that much.

@agessler I switch it to the official `backgroundColor` option.

2020-09-29 16:05 UTC, dcsaszar requested changes
Looks nice!

See comments. Also:

* [ ] Minor issue:
  * Open the gallery before confirming the cookie banner
  * Try to confirm the cookie banner, in order to be able to navigate the photo list
  * Expected: the cookie banner disappears
  * Actual: nothing happens when I click the buttons



* [ ] FYI Some style issues that are already in the original demo of react-bnb-gallery, so I guess we can't do much about them:
  * On mobile, when navigating the items, the photo list jumps up/down depending on the image description length.
  * On wide screens the photo list is right-aligned, where centered (around the current selection) would feel more natural.

2020-09-30 06:51 UTC, apepper commented on webpack.config.js
> +                plugins: ["@babel/plugin-syntax-dynamic-import"],
Nice!

2020-09-30 06:53 UTC, apepper commented on src/Widgets/ThumbnailGalleryWidget/ThumbnailGalleryWidgetComponent.js
> +            wrap={false}
There is an option issue about the `wrap` property: https://github.com/peterpalau/react-bnb-gallery/issues/42 . I wanted it to make it more explicit in the hopes, that a future version will switch the meaning of "wrap=true".

2020-09-30 07:11 UTC, apepper commented
REVIEW (d68325e)

Regarding the cookie consent issue: It seems to me, that this is an issue of either `react-bnb-gallery` and `react-cookie-consent`. I don't see an easy way to resolve the issue.

But since this only happens, if one opens the dialog I think we can live with this for now.

2020-09-30 10:22 UTC, dcsaszar commented on src/Widgets/ThumbnailGalleryWidget/ThumbnailGalleryWidgetComponent.js
> +            wrap={false}
The default behaviour is good. The rest is speculation and later versions may not match your hopes.

2020-09-30 10:26 UTC, dcsaszar commented
> But since this only happens, if one opens the dialog I think we can live with this for now.

In general, I agree this is a minor thing and can be fixed later, but:

Imagine a first-time visitor. They can scroll around the homepage and click anywhere.
As far as I can see there are only 2 areas where they cannot do this and are required to close the cookie banner:
* The footer
* An opened gallery photo list

Seen this way, 50% of the use cases for closing the cookie banner are broken.

2020-09-30 10:41 UTC, dcsaszar commented
As a quickfix:
If cookie box and gallery use the same `zIndex` it feels more natural, because then the gallery hides the cookiebox.

The gallery default appears to be 2000, for the cookie box we set 1000000.

2020-10-01 07:03 UTC, apepper commented
REVIEW (31432a4)

Fixed cookie banner issue: The gallery now overlaps the cookie banner fully.

2020-10-01 08:16 UTC, dcsaszar approved these changes
👍

2020-10-01 08:16 UTC, merged