webpack-dev-server update to 4.0.0 version
Scrivito/scrivito_example_app_js pull request #416
Opened 2021-08-20 11:34 UTC by kirkol

Tiny patch. Updated webpack-dev-server to 4.0.0.

**Note**: two depreciation warnings appear (DEP_WEBPACK_DEV_SERVER_CONSTRUCTOR and DEP_WEBPACK_DEV_SERVER_LISTEN). I wasn't able to find a root case :/ Npm installs packages seamlessly and project runs as it should, so I guess it can be a "general" warning even, if we don't use it in the code

2021-08-20 11:52 UTC, dcsaszar commented
Thanks for the PR. Looks good so far. I'll have a look at the deprecation thingies.

2021-08-21 08:41 UTC, dcsaszar requested changes
With `NODE_OPTIONS=--trace-deprecation` we can see the warnings are caused by `webpack-cli`.

* [x] Could you please update this, too?

2021-08-23 05:44 UTC, kirkol commented
Poof! Webpack-cli updated as well ;) Thank you for finding that! I set trace-deprecation flag in a wrong place and my Node didn't want to say anything xd

2021-08-23 07:56 UTC, dcsaszar approved these changes
Great! Thanks a lot!

2021-08-23 07:56 UTC, merged