Scrivito dark
Scrivito/scrivito_example_app_js pull request #429
Opened 2021-11-08 09:05 UTC by agessler

@apepper small fixes for https://github.com/Scrivito/scrivito_example_app_js/pull/428#discussion_r742330193

2021-11-08 12:53 UTC, dcsaszar requested changes
Looks mostly good. I'd like to see at least the double border situation improved.

2021-11-08 12:53 UTC, dcsaszar commented on src/assets/stylesheets/_social_cards.scss
> +  .seo_card_preview .creator { color: #5e86be;}
* [ ] FYI This color fails the contrast check https://webaim.org/resources/contrastchecker/?fcolor=5E86BE&bcolor=3F3F3F. In other places (e.g. changed attributes labels) we use a different blue (`#698cbe`), which passes at least for large text https://webaim.org/resources/contrastchecker/?fcolor=698cbe&bcolor=3F3F3F

2021-11-08 12:53 UTC, dcsaszar commented on src/assets/stylesheets/_social_cards.scss
> +.seo_card_input .input:focus { box-shadow: 0 0 0 2px #577fb6 inset; }
* [ ] We have two borders around focused inputs, which looks weird and is different from other UI elements:

|  ![image](https://user-images.githubusercontent.com/986170/140744053-d1a4fe8f-353d-4017-a10c-d10e19a2b102.png)  | ![image](https://user-images.githubusercontent.com/986170/140743988-3820704b-e6e5-4adb-9133-fe417a2189ac.png)  |
| -- | -- |
| ![image](https://user-images.githubusercontent.com/986170/140743841-31523320-71c2-4a0d-ab1e-5b9fe358714d.png)  |  ![image](https://user-images.githubusercontent.com/986170/140743911-69aa03a3-9a03-489d-9e2c-96233d72382c.png)  |

* [ ] FYI Not caused by the current changes, but I noticed it here: The text input color for an input with a warning is not grey, as it is for regular UI inputs with warnings.

2021-11-09 11:41 UTC, agessler commented
@dcsaszar Regarding last comment. I adapted the focus state and notice appearance - now the social tab looks same as built-in.
 ![focus](https://user-images.githubusercontent.com/710311/140917649-a92f1b35-ffcb-4c5d-813b-ad1d1392e247.gif)

2021-11-09 13:21 UTC, agessler commented
@dcsaszar last commit fixes this issue we talked about.

2021-11-09 13:36 UTC, dcsaszar approved these changes
👍

2021-11-09 13:37 UTC, merged