Bugfix: BlogPostNavigation can handle same date blog posts
Scrivito/scrivito_example_app_js pull request #442
Opened 2022-01-26 20:57 UTC by apepper

Previously the navigation did not work reliably, if one or more "publishedAt" had the exact same value (e.g. three blog posts all starting at the same day). Now this is fixed by also checking for "same date" entries.

2022-02-01 11:17 UTC, dcsaszar requested changes
General idea looks good, but the code does something unintended.

2022-02-01 11:17 UTC, dcsaszar commented on src/Components/BlogPost/BlogPostNavigation.js
> +    .order(["_id", "asc"])
* [ ] This would sort by by `_id` and `asc`
```suggestion
    .order("_id", "asc")
```

2022-02-01 11:17 UTC, dcsaszar commented on src/Components/BlogPost/BlogPostNavigation.js
> +    .order(["_id", "desc"])
* [ ] This would sort by by `_id` and `desc`
```suggestion
    .order("_id", "desc")
```

2022-02-08 11:02 UTC, apepper commented
REVIEW ([bca43a9](https://github.com/Scrivito/scrivito_example_app_js/pull/442/commits/bca43a9c6702a65bcef55145072f44f57029fd37))

2022-02-08 12:14 UTC, merged