Scrivito 1.32.0
Scrivito/scrivito_example_app_js pull request #518
Opened 2023-03-10 13:28 UTC by apepper

See https://www.scrivito.com/scrivito-js-sdk-1-32-0-released-6dc70e6597de3661 for all the greatness of the release.

2023-03-10 14:09 UTC, dcsaszar requested changes
Looks good aside from some rough edges.

See feedback for using the new `allowedTags` feature. I'm not even fully convinced this should be the new default for headlines since it adds a bit of complexity to both the app code and the editing UI. So far, this feature was only requested by large-scale customer projects. Maybe we should just leave the default as is?

2023-03-10 14:09 UTC, dcsaszar commented on src/Widgets/FactWidget/FactWidgetEditingConfig.js
> +  },
* [ ] Basically same as above. Customers typically ask for sub/sup in headlines. I think `string` is the better default everywhere else. If needed, devs can easily change from string to HTML on their own.

2023-03-10 14:09 UTC, dcsaszar commented on src/Widgets/HeadlineWidget/HeadlineWidgetClass.js
> +    headline: "html",
* [ ] If we do this, we must update the `id={speakingUrl(widget.get("headline"))}` part.

2023-03-13 10:00 UTC, apepper commented
I forced pushed [798d310](https://github.com/Scrivito/scrivito_example_app_js/pull/518/commits/798d3108d775e9ba0e068a2434464a585c06cd0c) . With that only the upgrade is included

2023-03-13 14:27 UTC, merged